### ISSUE TITLE
Inconsistent display covers

### ISSUE THREAD

**Issue by shaunjanssens** [oSoc15/biblo-app#2]
We need a consistent way of displaying covers. Every images the same height and the same width.

**Comment by wesobi** [comment]
I'll let the width of the pictures resize when they are too big (the height seems to consistently be 400px). Most of the time it's only off by < 10 pixels so it shouldn't look warped at all.

**Comment by shaunjanssens** [comment]
That hurts a designer! I will fix it, then I will kill you!
