### ISSUE TITLE
Visual enhancements

### ISSUE THREAD

**Issue by yungpanda** [oSoc15/biblo-app#23]
- When user swipes right or left, show indicator that he "liked" or "not liked" the theme
- Add 2 arrows in the beginning to make it more clear what to do
- Add more than "Hi this is Bieblo", maybe the theme name or a small description what to do
- Add padding to refresh button

**Comment by shaunjanssens** [comment]
Like / dislike theme: ok
More than "I'm Bieblo": need better copy
Refresh button: ok
